#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  3 13:39:16 2018

@author: imananwarzai
"""

import numpy as np
import cv2

img = cv2.imread('brain.png')
kernel = np.ones((9,9),np.uint8)
_, binary = cv2.threshold(img, 0, 255,
        cv2.THRESH_OTSU)
erode = cv2.erode(binary, kernel, iterations = 1)
temp = np.array(255, img.shape) 
temp[erode == 255] = img
if temp.min() > 0:
    blur = cv2.GaussianBlur(img,(21, 21),0)
else:
    blur = img.copy()
closing = cv2.morphologyEx(blur, cv2.MORPH_CLOSE, kernel)
img_gray = cv2.cvtColor(closing, cv2.COLOR_BGR2GRAY)    
_, img_bin = cv2.threshold(img_gray, 0, 255,
        cv2.THRESH_OTSU)
img_bin = cv2.morphologyEx(img_bin, cv2.MORPH_OPEN,
        np.ones((3, 3), dtype=int))
opening = cv2.morphologyEx(img_bin,cv2.MORPH_OPEN,kernel, iterations = 2)
sure_bg = cv2.dilate(opening,kernel,iterations=3)
dist_transform = cv2.distanceTransform(opening,cv2.DIST_L2,5)
ret, sure_fg = cv2.threshold(dist_transform,0.7*dist_transform.max(),255,0)
sure_fg = np.uint8(sure_fg)
unknown = cv2.subtract(sure_bg,sure_fg)
ret, markers = cv2.connectedComponents(sure_fg)
markers = markers+1
markers[unknown==255] = 0
markers = cv2.watershed(img,markers)
img[markers == -1] = [255,0,0]
cv2.imwrite('/Users/imananwarzai/Desktop/newimage.png', img)